### ISSUE TITLE
Incompatibility with concurrent-ruby 1.1.6?

### ISSUE THREAD

**Issue by kirs** [digital-fabric/polyphony#22]
First of all, thanks for acting on my previous bug reports 🙏 
I'd love to send PRs myself but for now my knowledge of the project is limited and all I can do is try to find bugs of the surface :)

I've attempted to plug polyphony into a simple project with activesupport. Then I found that the process would hang right before exiting.

Steps to reproduce:

1) Bump `concurrent-ruby` to `1.1.6`
2) Run the script:

```ruby
require 'bundler/setup'
require 'polyphony'

require 'concurrent' # we don't really need this but it's here to simulate side effects of requiring active_support/all
```

3) See the process hang.

I'm running it on `ruby 2.6.5p114`.

Downgrading concurrent-ruby to `1.1.5` is the current workaround.

**Comment by ciconia** [comment]
Thanks for your concise bug descriptions and code examples, it saves me a lot of time investigating the problems. The solution to this problem as described in the commit (c00009f) is to replace the core Ruby class `Queue` with the Polyphony queue implementation which is fiber-aware.

Let's see how far this can be taken. I'd be (pleasantly) surprised if concurrent-ruby can be made to work with Polyphony, but apparently there's quite a bunch of important gems that depend on it.
