### ISSUE TITLE
"Polyphony enables cross-thread communication using"...

### ISSUE THREAD

**Issue by wjordan** [digital-fabric/polyphony#29]
Hello, this seems like an interesting project! I was just reading the documentation overview and spotted a cliffhanger:

https://github.com/digital-fabric/polyphony/blame/master/docs/getting-started/overview.md#L117

> Nevertheless, Polyphony fully supports multithreading, with each thread having its own fiber run queue and its own libev event loop. In addition, Polyphony enables cross-thread communication using

_What_ does Polyphony use for cross-thread communication? The suspense is killing me 😅

**Comment by ciconia** [comment]
Thanks for noticing this. Cross-thread communication can be done simply by using the message passing mechanism.
