### ISSUE TITLE
YAML/Psych adapter

### ISSUE THREAD

**Issue by wjordan** [digital-fabric/polyphony#30]
`YAML` ([`psych`](https://github.com/ruby/psych)) uses a [C extension](https://github.com/ruby/psych/blob/c3e5cfc6658a0dcac9abb021625116a09419d2bc/ext/psych/psych_parser.c#L27-L41) that invokes `IO#read` to load data from a file directly, so it looks like this will need a custom adapter to work seamlessly with polyphony.

Here's a minimal test case:

```ruby
require 'yaml'
require 'tempfile'
file = Tempfile.new
file << 'hello: world'
file.close

puts YAML.load_file(file) # {"hello"=>"world"}

require 'polyphony'
puts YAML.load_file(file) # false
```

**Comment by ciconia** [comment]
No need for a YAML adapter, the problem turned out to be much more low-level than that. Thanks for reporting this!
