### ISSUE TITLE
Sleeping fibers sometimes fail to terminate

### ISSUE THREAD

**Issue by wjordan** [digital-fabric/polyphony#33]
Sometimes a fiber in a short `sleep` fails to terminate, here's a short test case that hangs on my machine:

```ruby
require 'bundler/setup'
require 'polyphony'

1000.times do |n|
  spin do
    loop do
      sleep 0.01
    end
  end
end

sleep 0.1
```

Some extra debugging shows half of the fibers failing to terminate:

```ruby
require 'bundler/setup'
require 'polyphony'

fibers = Array.new(1000) do |n|
  spin do
    loop do
      sleep 0.01
    end
  end
end

sleep 0.1
fibers.each(&:terminate)
until fibers.all? {|f| f.state == :dead}
  puts fibers.map(&:state).tally
  sleep 0.1
end
```

```
$ bundle exec ruby examples/core/xx-resource-pool.rb 
{:runnable=>1000}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>442, :runnable=>58}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>500}
{:dead=>500, :waiting=>430, :runnable=>70}
{:dead=>500, :waiting=>401, :runnable=>99}
[...]
```

**Comment by ciconia** [comment]
Thanks so much @wjordan for this report. The issue was a race condition where the anti-event starvation mechanism would be activated, causing timers to fire, which in turn would have overwritten the scheduled `Polyphony::Terminate` exception, causing it to be lost, and the fiber to continue running its loop.

**Comment by wjordan** [comment]
Thanks for the quick turnaround on fixes! I'll keep posting test cases like this as I continue hammering on the system if they are helpful.
