### ISSUE TITLE
IRB adapter does not work with Ruby 2.7.0

### ISSUE THREAD

**Issue by ciconia** [digital-fabric/polyphony#5]

**Comment by floriandejonckheere** [comment]
I managed to narrow down the offending code to a call to [`Ripper.parse`](https://github.com/ruby/ruby/blob/master/ext/ripper/lib/ripper/lexer.rb#L176).
The `Ripper.parse` method (defined [here](https://github.com/ruby/ruby/blob/master/parse.y#L14400)) uses a separate thread to parse the input.

Any thoughts on how this could be resolved?
