### ISSUE TITLE
Can the https / SSLSocket connection also use io_uring backend ?

### ISSUE THREAD

**Issue by Fedora7** [digital-fabric/polyphony#51]
Can https / SSLSocket connection also take advantage of the new  io_uring version of Backend_send(), Backend_read(), etc ? Thanks

**Comment by ciconia** [comment]
Yes: https://github.com/digital-fabric/polyphony/blob/master/lib/polyphony/extensions/openssl.rb

You can find a working HTTPS-capable Polyphony-based web server here: https://github.com/digital-fabric/tipi
