### ISSUE TITLE
Zlib::GzipReader raises "No thread set for fiber"

### ISSUE THREAD

**Issue by floriandejonckheere** [digital-fabric/polyphony#93]
When using Polyphony's I/O extensions, the following code raises an error after a seemingly arbitrary number of lines/bytes decompressed. It seems to vary depending on line length/number of lines and doesn't happen when using `GzipReader#readlines`. Perhaps a buffer being overrun somewhere?

```ruby
require "zlib"
require "polyphony"

# Write a file with 100 lines of 100 000 characters each
File.open("test.gz", "w+") do |file|
  gz = Zlib::GzipWriter.new(file)
  gz.write("#{'a' * 10_000}\n" * 1000)
  gz.close
end

# Read the file
gz = Zlib::GzipReader.open("test.gz")

it = gz.each_line

loop do
  it.next
rescue StopIteration
  break
rescue
  puts "Crashed at line #{gz.lineno}"

  raise
end
```

```
$ ruby test.rb
Crashed at line 166
test.rb:in `each_line': No thread set for fiber (RuntimeError)
	from test.rb:in `each'
	from test.rb:in `each'
```

**Comment by ciconia** [comment]
The following works fine:

```ruby
gz = Zlib::GzipReader.open('/tmp/test.gz')
gz.each_line do |l|
rescue
  trace "Crashed at line #{gz.lineno}"
  raise
end
```

There's some weird interaction between the Enumerator and the Polyphony. I'm investigating...

**Comment by ciconia** [comment]
Of course, `Enumerator` uses fibers to do external iteration. A fix is forthcoming.

**Comment by floriandejonckheere** [comment]
Thanks for the quick fix!
