### ISSUE TITLE
Fiber#supervise with watcher

### ISSUE THREAD

**Issue by floriandejonckheere** [digital-fabric/polyphony#94]
According to the documentation, it's possible to [set up a watcher](https://digital-fabric.github.io/polyphony/api-reference/fiber/#superviseopts----fiber) when supervising child fibers. However, I found that the supervision code ignores the `watcher:` argument. Was this functionality removed?
The documentation also doesn't mention `on_done:` and `on_error:`.

**Comment by ciconia** [comment]
The documentation is not up to date. The current implementation does not allow setting a watcher. You can instead monitor a fiber  manually by calling `Fiber#monitor`, e.g.:

```ruby
f = spin { sleep 1 }
f.monitor(Fiber.current)
msg = Fiber.current.monitor_mailbox.shift
```
